### ISSUE TITLE
形状冲突

### ISSUE THREAD

**Issue by xuanyin777** [nanowell/Differential-Transformer-PyTorch#1]
![image](https://github.com/user-attachments/assets/a4b4b56d-6bf5-4aed-9afb-24a3ac364a7c)

![image](https://github.com/user-attachments/assets/0006f403-7df5-431c-b9ca-e81794a9a13f)
初始化形状与计算时形状冲突

**Comment by KernelInterrupt** [comment]
我也发现这个问题了，有什么解决方法吗？

**Comment by KernelInterrupt** [comment]
我交了个pr，看作者收不收

**Comment by nanowell** [comment]
merged!
